fork = false
frame = "full"
idle = true
maximized = true
neovim-bin = "/etc/profiles/per-user/bahnasawy/bin/nvim"
no-multigrid = false
srgb = true
tabs = true
theme = "auto"
title-hidden = true
vsync = false
wsl = false

[font]
size = 14
normal = ["JetBrainsMono Nerd Font"]
hinting = "full"
edging = "antialias"
